- hosts: localhost
- name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/vagrant/kr8182/lesson6/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: vagrant
      group: vagrant
      mode: '0644'
