#!/bin/bash
scriptPath="/home/vagrant/2023-09-example/apps/webbooks/target"
logFile="/var/log/Launch_Scripts_launch_app.log"

echo "------------------------end of install postgres-------------------------------" >> $logFile
sudo java -jar $scriptPath/DigitalLibrary-0.0.1-SNAPSHOT.jar >> $logFile
wait
echo "------------------------end of install spring-------------------------------" >> $logFile