Vagrant.configure("2") do |config|
  config.vm.define "jen" do |jen|
    jen.vm.box = "ubuntu/focal64"
    jen.vm.hostname = 'jen'
    jen.vm.box_url = "ubuntu/focal64"

    jen.vm.network :private_network, ip: "192.168.56.101"
    jen.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    jen.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "jen"]
    end
  end
end