apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-world-app
  namespace: default
  labels:
    app: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: kr8182/kr8182:latest