apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: default
spec:
  selector:
    app: hello-world-app
  type: NodePort
  ports:
    - name: hello-world-app
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100